#是否隐藏该角色
Hide: false

#测试模式 也可以是试用角色 开启后 该角色的数据不会进行存储
#也无法修改这个角色的任何信息
TestModel: false

ArmsModelId: "warrior.bbmodel"

#等级机制
Level:
  #基础等级
  base: 1
  #经验来源追踪 是用于获取指定来源的经验 例如mm技能那边给予的经验就有这个经验组id  如果你填写了mm 下方也有mm 那才能给这个角色加经验
  # 原版经验为exp
  trace:
    - "exp"
    - "mm"
  # 关键等级设置
  # 只需对关键等级进行修改, 处于非关键等级时将自动读取下一个关键等级的信息
  key:
    10:
      condition:
      action:
      exp: 30
    25:
      condition:
      action:
      exp: 50

#装备机制
Equip:
  #key本身没有限制 但会有一些默认的功能
  #arms 会发放武器到快捷栏 并且会渲染动画用的模型
  arms:
    #js条件 具体的对象包在utils/script/wrapper包中查看
    #player 玩家对象
    #item 当前操作的物品对象
    condition: |-
      item.hasTag('Equip', '单手剑')
    #默认的物品 调用物品库物品
    #当玩家第一次获取角色时会使用这个物品填充
    defaultItemId: 测试武器


  武器:
    condition: |-
      item.hasTag('Equip', '单手剑')
    defaultItemId:

  帽子:
    #js条件
    condition: |-
      item.hasTag('Equip', '烈焰宝石')
    #初始物品ID 从物品库内拿取
    defaultItemId:
  上衣:
    condition: |-
      item.hasTag('Equip', '烈焰宝石')
    defaultItemId:
  药水:
    condition: |-
      item.hasTag('Medicine', '烈焰宝石')
    defaultItemId:
  药水效果1:
    condition: |-
      item.hasTag('Effect', '烈焰宝石')
    defaultItemId:
  药水效果2:
    condition: |-
      item.hasTag('Effect', '烈焰宝石')
    defaultItemId:

  大型烈焰宝石:
    condition: |-
      item.hasTag('Gem', '大型烈焰宝石')
    defaultItemId:
  小型烈焰宝石1:
    condition: |-
      item.hasTag('Gem', '烈焰宝石')
    defaultItemId:
  小型烈焰宝石2:
    condition: |-
      item.hasTag('Gem', '烈焰宝石')
    defaultItemId:

  大型苍穹宝石:
    condition: |-
      item.hasTag('Gem', '大型苍穹宝石')
    defaultItemId:
  小型苍穹宝石1:
    condition: |-
      item.hasTag('Gem', '苍穹宝石')
    defaultItemId:
  小型苍穹宝石2:
    condition: |-
      item.hasTag('Gem', '苍穹宝石')
    defaultItemId:

  大型潮汐宝石:
    condition: |-
      item.hasTag('Gem', '大型潮汐宝石')
    defaultItemId:
  小型潮汐宝石1:
    condition: |-
      item.hasTag('Gem', '潮汐宝石')
    defaultItemId:
  小型潮汐宝石2:
    condition: |-
      item.hasTag('Gem', '潮汐宝石')
    defaultItemId:



#角色升级的属性系统 必须添加 生命值 和 移动速度
Attributes:
  #属性key
  最大生命值:
    #自定义获取该属性的字符描述  如果不填或者没有这个参数 默认使用 属性key:属性值 的结果
    #这里的用途就是给你百分比加成用的 例如"生命上限:{value}%"
    string:
    #属性的基础值
    base: 15.0
    #每级增加的值
    per-level: 5.0
    #最大值
    max: 50.0
    #最小值
    min: 10.0
  移动速度:
    base: 1.2
    per-level: 0
  跳跃次数:
    base: 15
    per-level: 0
  物理伤害:
    base: 11.5
    per-level: 0
  暴击几率:
    string: "暴击几率:{value}%"
    base: 50
    per-level: 0
  暴击伤害:
    string: "暴击伤害:{value}%"
    base: 150
    per-level: 0
  攻击速度:
    string: "攻击速度:{value}%"
    base: 100
    per-level: 0

#所拥有的技能列表
Skills:
  #技能名称
  warrior_skill_main:
    trigger: "左键"
    #元数据 会覆盖技能配置本身的那个数据
    #技能配置那边的数据为全部默认使用的数据值 也可以添加自定义的
    #仅支持基础类型数据
    meta:
  warrior_skill_1:
    trigger: "技能1"
    meta:

  warrior_skill_2:
    trigger: "技能2"
    meta: